platform :ios, "8.0"

pod "MMDrawerController", "~> 0.5.7"
pod "TSMessages", "~> 0.9.11"
pod "AFNetworking", "~> 3.0.3"
pod "DGActivityIndicatorView", "~> 1.0"
pod "MagicalRecord", "~> 2.3.0"
pod "VK-ios-sdk", "~> 1.3.1"
pod "libextobjc"
pod "MarqueeLabel", "~> 2.4.1"